[project]
name = "fastmcp-demo-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HAmzaaider", email = "kohat3067@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "aiosqlite>=0.22.1",
    "fastmcp>=4.0.4",
]

[project.scripts]
fastmcp-demo-server = "fastmcp_demo_server:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
